#!/usr/bin/env python
#
# [SNIPPET_NAME:        Workspace Switcher Application Indicator for Elementary OS            ]
# [SNIPPET_CATEGORIES:  Application Indicator                                                 ]
# [SNIPPET_DESCRIPTION: Simple workspace switcher for Elementary OS                           ]
# [SNIPPET_AUTHOR:      Tamas Hegedus <hegedus.t@gmail.com>                                   ]
# [SNIPPET_BASED_ON:    George Dumitrescu's indicator-workspaces                              ]
# [                     https://launchpad.net/indicator-workspaces                            ]
# [                     Icons from (some gnome package): tbd                                  ]
# [SNIPPET_DOCS:        https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators   ]
# [SNIPPET_LICENSE:     GPL]

import pygtk
pygtk.require('2.0')
from gi.repository.GLib import Variant
from gi.repository.Gio import Settings
import gtk
import appindicator
import wnck
import time
import tempfile
import os
import sys


ICON_THEME = gtk.icon_theme_get_default()
OWN_ICON_DIR = sys.argv[1] if len(sys.argv) > 1 and os.path.isdir(sys.argv[1])  else os.path.dirname( os.path.realpath(__file__) )+os.path.sep+'icons'+os.path.sep


class AppIndicatorWorkspace:
    
    def __init__(self):
        
        self.lockfile = os.path.normpath(tempfile.gettempdir() + '/' + os.path.basename(__file__) + '.lock')
        import fcntl
        self.fp = open(self.lockfile, 'w')
        try:
            fcntl.lockf(self.fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except IOError:
            print "\nAnother instance is already running, quitting."
            sys.exit(-1)

        # Test if dynamic workspaces is enabled
        behavior_setting = "org.pantheon.desktop.gala.behavior"
        behavior_key     = "dynamic-workspaces"
        behavior = Settings.new(behavior_setting)
        if behavior.get_boolean(behavior_key):
            print "Dynamic workspaces must be switched off\n"
            print "You can do this through the command line 'gsettings set %s %s false'\n" % (
                    behavior_setting, behavior_key)
            sys.exit(-1)

        self.ind = appindicator.Indicator("indicator-eos-workspaces", "", appindicator.CATEGORY_APPLICATION_STATUS)

        self.ind.set_status (appindicator.STATUS_ACTIVE)
        
        self.scr = wnck.screen_get_default()
        self.scr.force_update()

        while gtk.events_pending():
            gtk.main_iteration()
            
        self.initialize()
        self.set_icon(self.active_desktop)

        self.scr.connect('active-workspace-changed', self.ws_changed)

    def set_icon(self, ws = None):
        ic = "workspace-%d" % (ws+1)
        if ICON_THEME.lookup_icon(ic, 24, 0):
            self.ind.set_icon(ic)
        else:
            self.ind.set_icon_theme_path (self.icon_directory(OWN_ICON_DIR))
            self.ind.set_icon(ic)

    def icon_directory(self, icon_path = __file__):
         return os.path.realpath(os.path.expanduser(icon_path)) + os.path.sep

    def _get_active_desktop(self):
        ws = self.scr.get_active_workspace()
        return ws.get_number()
    active_desktop = property(_get_active_desktop)

    def _get_num_desktops(self):
        return self.num_workspaces
    num_desktops = property(_get_num_desktops)
    
    def update(self):
        self.ws = self.scr.get_active_workspace()
        self.num_workspaces = self.scr.get_workspace_count()
    
    def initialize(self):
        
        # variable init
        self.update()        
        
        # create a menu
        self.menu = gtk.Menu()
        self.aradio = []

        workspace_list_settings = Settings.new("org.gnome.desktop.wm.preferences")
        workspace_list_key      = "workspace-names"
        workspace_list          = workspace_list_settings.get_value(workspace_list_key).unpack()
        
        # If there are no named desktops, generate them and save
        if not len(workspace_list):
            workspace_list = ["Workspace %d" % x for x in range(1, self.num_workspaces+1)]
            workspace_list_settings.set_value(workspace_list_key, Variant("as", workspace_list))
        
        # create items for the menu 
        for number,workspace_name in enumerate(workspace_list):
            if number == 0:
                self.aradio.append(gtk.RadioMenuItem(None, workspace_name))

            else:
                self.aradio.append(gtk.RadioMenuItem(self.aradio[number-1], workspace_name))
            if number == self.ws:
                self.aradio[number].set_active(True)
            self.aradio[number].connect("activate", self.switch_to_desktop, number)
            self.aradio[number].show()
            self.menu.append(self.aradio[number])
                    
        self.menu.show()
        self.ind.set_menu(self.menu)
        # bug : https://bugs.launchpad.net/indicator-application/+bug/1075152
        #self.ind.connect("scroll-event", self.scroll_to_desktop)

    def clear(self):
        self.aradio = []
        self.initialize()
        
    def scroll_to_desktop(self, arg1, arg2, arg3):
        self.update()
        if arg3 == 0:
            if (self.active_desktop > 0):
                self.set_desktop(self.active_desktop-1)
        else:
            if (self.active_desktop < self.num_desktops-1):
                self.set_desktop(self.active_desktop+1)
            
        
    def switch_to_desktop(self, obj, number):
        self.update()
        if self.aradio[number].get_active():
            timestamp = int(time.time())
            self.scr.get_workspace(number).activate(timestamp)
            
    def set_desktop (self, number):
        timestamp = int(time.time())
        self.scr.get_workspace(number).activate(timestamp) 
        
    def ws_changed(self, scrm, opt = False):
        self.clear()
        self.set_icon(self.active_desktop)
        if not self.aradio[self.active_desktop].get_active():
            self.aradio[self.active_desktop].set_active(True)
        
    def preferences(self, opt):
        subprocess.Popen("indicator-workspaces-preferences")
    
    def quit(self, widget, data=None):
        gtk.main_quit()
        
def main():
    gtk.main()

if __name__ == "__main__":
    indicator = AppIndicatorWorkspace()
    main()
